---
title: "Shiny App Pitch Presentation"
author: "P. Semple"
date: "2023-10-17"
output: ioslides_presentation
runtime: shiny
---


## Introduction

The purpose of this Shiny App is to complete Developing Data Products Project. This peer assessed assignment has two parts. First, to create a Shiny application with associated supporting documentation and deploy it on Rstudio's servers. Second, to use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about the application created. 
Overall Functionality:

The Shiny app was created as an adaptable tool for data analysis and prediction. It allows users to interact with data from the mtcars dataset and makes predictions about miles per gallon (MPG) for varying scenarios. Users can interact with it by selecting variables for data analysis and entering values in order to predict MPG. Data analysis results and prediction outputs are displayed in the respective output sections.



## Shiny App - User Interface 

The app has two main tabs within a navbarPage: "Data Analysis" and "Prediction."  The "Data Analysis" tab is defined using tabPanel and contains a sidebarLayout with two panels: a sidebarPanel and a mainPanel. The sidebarPanel includes input elements that users can interact with. The mainPanel is used to display the data analysis results.  In the "Data Analysis" tab, users can select a variable using the selectinput widget.  Clicking the "Analyze Data" button in the "Data Analysis" tab will provide a summary of the selected variable.

Within the "Prediction" tab, there is another sidebarLayout with sidebarPanel and mainPanel. The sidebarPanel contains prediction input elements and the mainPanel displays prediction output.  In the "Prediction tab, users can input a value for predicting MPG and click the "Make Prediction" button.  Clicking the "Make Prediction" button will display the prediction result.  




## Shiny App - Server Logic

The server logic defines how the app responds to user input. The code structure given is for a Shiny app that provides basic data analysis and prediction functionality. It responds to user interactions and controls the behavior of the app.

For data analysis, an event handler (observeEvent) listens for clicks on the "Analyze Data" button. When clicked, it computes a summary of the selected variable from the mtcars dataset and renders the result using renderPrint.

The ui.R, server.R and Readme.md files are located on Github at: https://github.com/Penhugh89/DDP-Project.
  
   


## App Demo

```{r setup, echo=FALSE}
library(shiny)
library(rsconnect)
data("mtcars")
list <- names(mtcars)
reglist <- setdiff(list, c('am', 'carb', 'gear', 'mpg', 'vs'))


# Define the UI
ui <- fluidPage(
  navbarPage("Data analysis and MPG prediction using Mtcars dataset",
    tabPanel("Data Analysis", 
      sidebarLayout(
        sidebarPanel(
          selectInput("var1", "Select Variable", choices = reglist),
          selectInput("trans", "Select transmission:",
            c(" " = 2, "Manual" = 1, "Automatic" = 0),
            selected = NULL,
            multiple = F
          ),
          submitButton("Submit"),
          h5(textOutput("doc"))
        ),
        mainPanel(
          h3(textOutput("caption")),
          tabsetPanel(type = "tabs",
            tabPanel("Scatterplot", br(), plotOutput("scatterplot")),
            tabPanel("Boxplot", br(), plotOutput("boxplot")),
            tabPanel("Data", br(), tableOutput("results"))
          )
        )
      )
    ),
    
    tabPanel("Prediction Model", fluid = TRUE,
      sidebarLayout(
        sidebarPanel(
          selectInput("id1", "Select transmission:",
            c("Manual" = 1, "Automatic" = 0)
          ),
          sliderInput("id2", 'Enter hp of the car', min = 50, max = 400, value = 50),
          sliderInput("id3", 'Enter weight of the car', min = 1.0, max = 6.1, value = 1.0),
          submitButton("Submit"),
          h5(textOutput("preddoc"))
        ),
        mainPanel(
          tabsetPanel(type = "tabs",
            tabPanel("ModelSummary", br(), verbatimTextOutput ("summary")),
            tabPanel("VarImp", br(), verbatimTextOutput ("varimp")),
            tabPanel("Prediction", br(), textOutput("pred2"))
          )
        )
      )
    )
  )
)


# Define the Server logic
server <- function(input, output) {
  observeEvent(input$var1, {
    print(paste0("You have chosen: ", input$id2))
  })
  
   output$id1<-renderText(input$var1)
  
  formulaText <- reactive({
    paste('mpg', "~", input$var1)
  })
  
  Text <- reactive({
    paste('Relation between mpg and', input$var1 , 'by transmission type')
    
  })

  output$caption <- renderText({
    Text()
  })

  output$doc <- renderText({
    "Choose a variable from the dropdown box and view the relationship between the variable and MPG.  Select a transmission 
     type or leave the box empty.  If a transmission type is not chosen, the data will show the relationship between the 
     selected variable and MPG.  The main panel tab shows the scatterplot, boxplot and the related data depending on the 
     variable selected.  Press the submit button each time a variable is selected."
  })
  
  output$preddoc <- renderText({
       "A multiple linear regression model which included all the independent variables, was built.  The details of the model 
    can be seen by clicking on the model summary tab.  The explanatory variables were noted to be am, qsec, and wt.  That 
    is, these variables were statistically significant as they have the lowest p values.  
        By clicking the VarImp tab, the same predictors (am, qsec, and wt ) can be seen as more statistically significant 
    than the other predictors. These three variables were used to build a second model.  By selecting any of these variables
    from the side bar panel, users can see the predicted MPG. Press the submit button each time a variable is selected to 
    view the predicted MPG."
  })
  
  output$results <- renderTable({
    if(input$trans==0){
      mtcars_output=mtcars[mtcars$am==0,]
      
    } else if (input$trans==1){
      mtcars_output=mtcars[mtcars$am==1,]
      
    }else {mtcars_output=mtcars
    }
    
    mtcars_output
  })
  
  output$scatterplot <- renderPlot({
    if(input$trans==0){
      mtcars1=mtcars[mtcars$am==0,]
    } else if (input$trans==1){
      mtcars1=mtcars[mtcars$am==1,]
    }else {mtcars1=mtcars}
    print(plot(as.formula(formulaText()),data=mtcars1) )
  })
  output$boxplot <- renderPlot({
    if(input$trans==0){
      mtcars1=mtcars[mtcars$am==0,]
    } else if (input$trans==1){
      mtcars1=mtcars[mtcars$am==1,]
    }else {mtcars1=mtcars}
    print(boxplot(as.formula(formulaText()),data=mtcars1,ylab ="mpg", xlab =input$var1) )
  }) 
 
  model1 <- lm(mpg ~ ., data = mtcars)
  model2 <- lm(mpg ~ am+hp+wt, data = mtcars)
  model2pred <- reactive({
    
    aminput <- as.numeric(input$id1)
    hpinput <- input$id2
    wtinput <- input$id3
    predict(model2, newdata = data.frame(am=aminput,hp=hpinput,wt=wtinput))
    
  })
  
  output$summary <- renderPrint ({
    
    summary(model1)
    
  })  
  output$varimp <- renderPrint ({                                                                       
    
    varImp(model1, scale = FALSE)                                                                        
    
  }) 
  
  output$pred2 <- renderText({
    
    model2pred()
    
  })
}

shinyApp(ui, server)
rsconnect::deployDoc(
  document = ui,
  documentName = "Shiny_App_Pitch_Presentation",
  account = "pcr1989"
)

```




